// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJdG5bBfIl_z1UpnnGUqYF90_u6YEwkX8',
    appId: '1:842866677075:web:25dbe82a7cf72d45e2fda6',
    messagingSenderId: '842866677075',
    projectId: 'chatapp-7bf56',
    authDomain: 'chatapp-7bf56.firebaseapp.com',
    storageBucket: 'chatapp-7bf56.appspot.com',
    measurementId: 'G-VZD7PJH17Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-YQHVP0sw9UEVQogJsN2VtvTWlFed4jw',
    appId: '1:842866677075:android:f5bfeafd83bc62d3e2fda6',
    messagingSenderId: '842866677075',
    projectId: 'chatapp-7bf56',
    storageBucket: 'chatapp-7bf56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb3lWM5xc4COPIX8rtv1jhRLh2WSxv018',
    appId: '1:842866677075:ios:e20a53a728e4458fe2fda6',
    messagingSenderId: '842866677075',
    projectId: 'chatapp-7bf56',
    storageBucket: 'chatapp-7bf56.appspot.com',
    iosClientId: '842866677075-7rg35g9qbfeqfb0a63dag7t2c9tkp46j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
